stages:
  - testing
  - history
  - allure_report
  - deploy_on_page


docker_job:
  stage: testing
  tags:
    - docker
  image: python:3.11-alpine
  services:
    - selenium/standalone-chrome
    - selenium/standalone-firefox
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest ./tests/
  artifacts:
    name: test_report
    paths:
      - ./allure_result
    expire_in: 1 day
  allow_failure: true



history:
  stage: history
  tags:
    - docker
  image: storytel/alpine-bash-curl
  script:
    - 'curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/$PROJECT_ID/jobs/artifacts/master/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - apk add unzip
    - unzip -o ./artifacts.zip
    - chmod -R 777 public
    - cp -r ./public/history ./allure_result
  allow_failure: true
  artifacts:
      untracked: true
      paths:
        - ./allure_result
      expire_in: 1 day
  rules:
    - when: always


allure_job:
  stage: allure_report

  tags:
    - docker


  image: frankescobar/allure-docker-service

  script:
     - allure generate -c ./allure_result -o ./allure_report
  artifacts:
    untracked: true
    paths:
      - ./allure_result
      - ./allure_report
    expire_in: 1 day
  rules:
    - when: always


pages:
  stage: deploy_on_page
  tags:
    - docker
  before_script:
    - rm -rf public
  script:
    - mkdir public
    - mv ./allure_report/* public

  artifacts:
    paths:
      - public
  rules:
    - when: always